# Generated by Django 5.0.4 on 2024-05-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimerApp', '0003_estudiante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='camada',
            new_name='grupo',
        ),
    ]
