# Generated by Django 5.0.4 on 2024-05-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimerApp', '0004_rename_camada_curso_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='curso',
        ),
    ]
